package com.tecmanutencao.app.ui.orcamento

import android.content.Intent
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.ArrowBack
import androidx.compose.material.icons.filled.Delete
import androidx.compose.material.icons.filled.Download
import androidx.compose.material.icons.filled.Edit
import androidx.compose.material.icons.filled.PictureAsPdf
import androidx.compose.material.icons.filled.Share
import androidx.compose.material3.Button
import androidx.compose.material3.ButtonDefaults
import androidx.compose.material3.Card
import androidx.compose.material3.CardDefaults
import androidx.compose.material3.DropdownMenuItem
import androidx.compose.material3.ExperimentalMaterial3Api
import androidx.compose.material3.ExposedDropdownMenuBox
import androidx.compose.material3.ExposedDropdownMenuDefaults
import androidx.compose.material3.Icon
import androidx.compose.material3.IconButton
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.OutlinedButton
import androidx.compose.material3.OutlinedTextField
import androidx.compose.material3.Scaffold
import androidx.compose.material3.Text
import androidx.compose.material3.TopAppBar
import androidx.compose.material3.TopAppBarDefaults
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.collectAsState
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.rememberCoroutineScope
import androidx.compose.runtime.setValue
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.lifecycle.viewmodel.compose.viewModel
import com.tecmanutencao.app.domain.model.StatusOrcamento
import com.tecmanutencao.app.ui.components.ConfirmDialog
import com.tecmanutencao.app.util.DateUtils
import com.tecmanutencao.app.util.NumberUtils
import com.tecmanutencao.app.util.PdfGenerator
import kotlinx.coroutines.launch
import java.io.File

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun OrcamentoDetailScreen(
    orcamentoId: Long,
    onEdit: () -> Unit,
    onBack: () -> Unit,
    viewModel: OrcamentoViewModel = viewModel(factory = OrcamentoViewModel.Factory(
        (LocalContext.current.applicationContext as com.tecmanutencao.app.TecManutencaoApp).orcamentoRepository,
        (LocalContext.current.applicationContext as com.tecmanutencao.app.TecManutencaoApp).clienteRepository,
        (LocalContext.current.applicationContext as com.tecmanutencao.app.TecManutencaoApp).equipamentoRepository
    ))
) {
    val uiState by viewModel.uiState.collectAsState()
    val context = LocalContext.current
    val scope = rememberCoroutineScope()
    var showDeleteDialog by remember { mutableStateOf(false) }
    var statusExpanded by remember { mutableStateOf(false) }
    var pdfGenerated by remember { mutableStateOf<File?>(null) }

    LaunchedEffect(orcamentoId) {
        viewModel.loadOrcamento(orcamentoId)
    }

    LaunchedEffect(uiState.saveSuccess) {
        if (uiState.saveSuccess) {
            viewModel.resetSaveSuccess()
        }
    }

    if (showDeleteDialog) {
        ConfirmDialog(
            title = "Excluir Orçamento",
            message = "Tem certeza que deseja excluir este orçamento?",
            confirmText = "Excluir",
            onConfirm = {
                showDeleteDialog = false
                viewModel.deleteOrcamento()
                onBack()
            },
            onDismiss = { showDeleteDialog = false }
        )
    }

    Scaffold(
        topBar = {
            TopAppBar(
                title = { Text(uiState.currentOrcamento.numeroOrcamento) },
                navigationIcon = {
                    IconButton(onClick = onBack) {
                        Icon(Icons.Default.ArrowBack, contentDescription = "Voltar")
                    }
                },
                actions = {
                    IconButton(onClick = onEdit) {
                        Icon(Icons.Default.Edit, contentDescription = "Editar")
                    }
                    IconButton(onClick = { showDeleteDialog = true }) {
                        Icon(Icons.Default.Delete, contentDescription = "Excluir")
                    }
                },
                colors = TopAppBarDefaults.topAppBarColors(
                    containerColor = MaterialTheme.colorScheme.primary,
                    titleContentColor = MaterialTheme.colorScheme.onPrimary,
                    navigationIconContentColor = MaterialTheme.colorScheme.onPrimary,
                    actionIconContentColor = MaterialTheme.colorScheme.onPrimary
                )
            )
        }
    ) { padding ->
        Column(
            modifier = Modifier
                .fillMaxSize()
                .padding(padding)
                .verticalScroll(rememberScrollState())
                .padding(16.dp)
        ) {
            // Status
            ExposedDropdownMenuBox(
                expanded = statusExpanded,
                onExpandedChange = { statusExpanded = it }
            ) {
                OutlinedTextField(
                    value = uiState.currentOrcamento.status.descricao,
                    onValueChange = {},
                    readOnly = true,
                    label = { Text("Status") },
                    trailingIcon = { ExposedDropdownMenuDefaults.TrailingIcon(expanded = statusExpanded) },
                    modifier = Modifier.fillMaxWidth().menuAnchor()
                )
                ExposedDropdownMenu(
                    expanded = statusExpanded,
                    onDismissRequest = { statusExpanded = false }
                ) {
                    StatusOrcamento.entries.forEach { status ->
                        DropdownMenuItem(
                            text = { Text(status.descricao) },
                            onClick = {
                                viewModel.updateStatus(status)
                                statusExpanded = false
                            }
                        )
                    }
                }
            }

            Spacer(modifier = Modifier.height(16.dp))

            // Client Info
            Card(
                modifier = Modifier.fillMaxWidth(),
                colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surfaceVariant)
            ) {
                Column(modifier = Modifier.padding(16.dp)) {
                    Text("Dados do Cliente", style = MaterialTheme.typography.titleMedium, fontWeight = FontWeight.Bold)
                    DetailRow("Nome", uiState.currentCliente.nomeCompleto)
                    DetailRow("CPF/CNPJ", uiState.currentCliente.cpfCnpj)
                    DetailRow("Telefone", uiState.currentCliente.telefone)
                    DetailRow("WhatsApp", uiState.currentCliente.whatsapp)
                    DetailRow("E-mail", uiState.currentCliente.email)
                    DetailRow("Endereço", uiState.currentCliente.endereco)
                }
            }

            Spacer(modifier = Modifier.height(12.dp))

            // Equipamento Info
            Card(
                modifier = Modifier.fillMaxWidth(),
                colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surfaceVariant)
            ) {
                Column(modifier = Modifier.padding(16.dp)) {
                    Text("Equipamento", style = MaterialTheme.typography.titleMedium, fontWeight = FontWeight.Bold)
                    DetailRow("Tipo", uiState.currentEquipamento.tipoMaquina.descricao)
                    DetailRow("Marca", uiState.currentEquipamento.marca)
                    DetailRow("Modelo", uiState.currentEquipamento.modelo)
                    DetailRow("Nº Série", uiState.currentEquipamento.numeroSerie)
                    DetailRow("Problema", uiState.currentEquipamento.problemaInformado)
                    DetailRow("Obs. Técnico", uiState.currentEquipamento.observacoesTecnico)
                }
            }

            Spacer(modifier = Modifier.height(12.dp))

            // Service Info
            Card(
                modifier = Modifier.fillMaxWidth(),
                colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surfaceVariant)
            ) {
                Column(modifier = Modifier.padding(16.dp)) {
                    Text("Serviço", style = MaterialTheme.typography.titleMedium, fontWeight = FontWeight.Bold)
                    DetailRow("Descrição", uiState.currentOrcamento.descricaoServico)
                    DetailRow("Valor", NumberUtils.formatCurrency(uiState.currentOrcamento.valorServico))
                    DetailRow("Pagamento", uiState.currentOrcamento.formaPagamento.descricao)
                    DetailRow("Observações", uiState.currentOrcamento.observacoes)
                }
            }

            Spacer(modifier = Modifier.height(16.dp))

            // PDF Actions
            Text(
                "Ações do PDF",
                style = MaterialTheme.typography.titleMedium,
                fontWeight = FontWeight.Bold,
                modifier = Modifier.padding(bottom = 8.dp)
            )

            Row(modifier = Modifier.fillMaxWidth()) {
                Button(
                    onClick = {
                        scope.launch {
                            val empresaConfig = (context.applicationContext as com.tecmanutencao.app.TecManutencaoApp).empresaConfigRepository.getConfigOnce()
                            pdfGenerated = PdfGenerator.generateOrcamentoPdf(
                                context = context,
                                orcamento = uiState.currentOrcamento,
                                cliente = uiState.currentCliente,
                                equipamento = uiState.currentEquipamento,
                                empresaConfig = empresaConfig
                            )
                        }
                    },
                    modifier = Modifier.weight(1f)
                ) {
                    Icon(Icons.Default.PictureAsPdf, contentDescription = null)
                    Text("  Gerar PDF", modifier = Modifier.padding(start = 4.dp))
                }
            }

            if (pdfGenerated != null) {
                Spacer(modifier = Modifier.height(12.dp))

                Button(
                    onClick = {
                        val file = pdfGenerated ?: return@Button
                        val uri = androidx.core.content.FileProvider.getUriForFile(
                            context,
                            "${context.packageName}.fileprovider",
                            file
                        )
                        val intent = Intent(Intent.ACTION_VIEW).apply {
                            setDataAndType(uri, "application/pdf")
                            addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
                        }
                        context.startActivity(intent)
                    },
                    modifier = Modifier.fillMaxWidth(),
                    colors = ButtonDefaults.buttonColors(
                        containerColor = MaterialTheme.colorScheme.secondary
                    )
                ) {
                    Icon(Icons.Default.Download, contentDescription = null)
                    Text("  Visualizar PDF", modifier = Modifier.padding(start = 4.dp))
                }

                Spacer(modifier = Modifier.height(8.dp))

                Button(
                    onClick = {
                        val file = pdfGenerated ?: return@Button
                        val uri = androidx.core.content.FileProvider.getUriForFile(
                            context,
                            "${context.packageName}.fileprovider",
                            file
                        )
                        val intent = Intent(Intent.ACTION_SEND).apply {
                            type = "application/pdf"
                            putExtra(Intent.EXTRA_STREAM, uri)
                            addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
                        }
                        context.startActivity(Intent.createChooser(intent, "Compartilhar PDF"))
                    },
                    modifier = Modifier.fillMaxWidth(),
                    colors = ButtonDefaults.buttonColors(
                        containerColor = MaterialTheme.colorScheme.tertiary
                    )
                ) {
                    Icon(Icons.Default.Share, contentDescription = null)
                    Text("  Compartilhar PDF", modifier = Modifier.padding(start = 4.dp))
                }
            }
        }
    }
}

@Composable
private fun DetailRow(label: String, value: String) {
    if (value.isNotEmpty()) {
        Row(
            modifier = Modifier
                .fillMaxWidth()
                .padding(vertical = 2.dp)
        ) {
            Text(
                text = "$label: ",
                style = MaterialTheme.typography.bodyMedium,
                fontWeight = FontWeight.SemiBold,
                color = MaterialTheme.colorScheme.onSurfaceVariant
            )
            Text(
                text = value,
                style = MaterialTheme.typography.bodyMedium,
                color = MaterialTheme.colorScheme.onSurface
            )
        }
    }
}
